from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from shlex import quote as shquote

from .domain import SUPPORTED_MACOS, VmConfig
from .downloader import RESTRICTEVENTS_URL, RESTRICTEVENTS_ZIP
from .smbios_planner import _sanitize_smbios

log = logging.getLogger(__name__)

__all__ = [
    "render_script",
    "_plist_patch_script",
    "_apple_id_bypass_patch_keys",
    "_build_oc_disk_script",
]

# Imported by planner for use in _opencore_steps
_APPLE_OSK = "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"

_OC_DISK_SIZE_MB = 1024

# A macOS install reboots two or three times, and the picker lists the attached
# recovery disk ahead of the installer. Any non-zero timeout therefore auto-boots
# recovery on every reboot and the install silently never finishes. 0 disables
# auto-boot entirely (OpenCore: "Set to 0 to disable"), so the picker waits for a
# choice instead of making the wrong one. post-install restores INSTALLED once
# recovery is detached and there is only one sane entry left to boot.
PICKER_TIMEOUT_INSTALL = 0
PICKER_TIMEOUT_INSTALLED = 15

# revblock=pci is the documented way to ask RestrictEvents to block
# MemorySlotNotification and ExpansionSlotNotification, the processes behind the
# "Memory Modules Misconfigured" banner MacPro7,1 shows because a VM has no DIMM
# slots. It is set because it is the correct configuration, but be clear that on
# Sequoia it does NOT currently suppress the banner.
#
# Measured on a clean Sequoia 15.7.9 guest with every documented precondition
# satisfied: Lilu 1.6.8, RestrictEvents 1.1.6 and VirtualSMC all loaded,
# hw.model MacPro7,1, SIP fully disabled, and revblock=pci live in boot-args.
# MemorySlotNotification still ran (pid 540 from boot) and still posted the
# notification. RestrictEvents' process blocking appears broken on this macOS,
# and 1.1.6 is the newest release. Treat the banner as cosmetic and unfixed;
# PlatformInfo -> CustomMemory is the kext-free alternative, untested here.
BOOT_ARGS_BASE = "keepsyms=1 debug=0x100 revblock=pci"


def _partprobe_retry_snippet(loop_var: str) -> str:
    """Return bash snippet that retries partprobe up to 10 times for slow storage."""
    return (
        f"partprobe ${loop_var} 2>/dev/null; "
        f"for _i in $(seq 1 10); do ls ${{{loop_var}}}p* &>/dev/null && break; "
        f"sleep 1; partprobe ${loop_var} 2>/dev/null; "
        f"blockdev --rereadpt ${loop_var} 2>/dev/null; done"
    )


def render_script(config: VmConfig, steps: list) -> str:
    meta = SUPPORTED_MACOS[config.macos]
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        f"# Generated by osx-proxmox-next on {now}",
        f"# Target: {meta['label']} (channel={meta['channel']})",
        f"# VMID: {config.vmid}",
        "",
    ]
    for idx, step in enumerate(steps, start=1):
        lines.append(f"echo '[{idx}/{len(steps)}] {step.title}'")
        lines.append(step.command)
        lines.append("")
    return "\n".join(lines)


def _amd_plist_keys() -> str:
    """Return inline python fragment to set AMD CPU power management quirks."""
    return (
        "kq=p[\"Kernel\"][\"Quirks\"]; "
        "kq[\"AppleCpuPmCfgLock\"]=True; "
        "kq[\"AppleXcpmCfgLock\"]=True; "
    )


# Swap two sysctl names in the kernel's cstring table (same technique
# OpenCore-Legacy-Patcher uses, run in reverse so the flag reads 0):
#
#   1. rename the real kern.hv_vmm_present OID to hibernatecount
#   2. rename the real kern.hibernatecount OID to hv_vmm_present
#
# It is a true swap, not a rename-to-junk: no name is invented, no name
# disappears, and the count of each stays 1. Renaming the real OID to
# something like hv_vmm_hidden_ would leave a sysctl advertising itself as
# "running on a vmm" with value 1, which fingerprints the guest harder than
# the flag being hidden hides it.
#
# The value now behind kern.hv_vmm_present is gIOHibernateCount, which is 0 at
# boot and increments only in IOHibernateDone, i.e. on waking from a sleep that
# actually opened a hibernate file. It is NOT a constant. It stays 0 here
# because we ship the MacPro7,1 SMBIOS (see smbios.py) and desktop Macs default
# to hibernatemode=0, which never opens that file. A guest switched to
# hibernatemode=3 would report a non-zero VM flag after its first hibernate
# cycle, until the next cold boot.
#
# Step 1 is not optional. Without it both OIDs are registered under the name
# hv_vmm_present and sysctlbyname() still returns the real one (1), so Apple's
# attestation keeps seeing a VM and Apple ID sign-in fails with
# "Verification Failed".
#
# Each pair below is a NUL-separated run of adjacent strings in the kernel's
# cstring section, so the neighbour anchors the match and keeps it unique.
# Replacements are the same byte length, which OpenCore requires. Sources:
# bsd/kern/hvg_sysctl.c and iokit/Kernel/IOHibernateIO.cpp; both runs occur
# exactly once in Darwin 24.x (Sequoia) and 25.x (Tahoe) kernels.
_APPLE_ID_BYPASS_PATCHES = (
    (
        "Apple ID VM bypass - hide real hv_vmm_present",
        # b"boot session UUID\0hv_vmm_present\0"
        "626f6f742073657373696f6e20555549440068765f766d6d5f70726573656e7400",
        # b"boot session UUID\0hibernatecount\0"
        "626f6f742073657373696f6e20555549440068696265726e617465636f756e7400",
    ),
    (
        "Apple ID VM bypass - hv_vmm_present",
        # b"hibernatehidready\0hibernatecount\0"
        "68696265726e61746568696472656164790068696265726e617465636f756e7400",
        # b"hibernatehidready\0hv_vmm_present\0"
        "68696265726e61746568696472656164790068765f766d6d5f70726573656e7400",
    ),
)


def _apple_id_bypass_patch_keys() -> str:
    """Return inline python fragment to add kernel patches that bypass Apple's VM detection.

    macOS ends up reading hv_vmm_present=0 (the hibernate counter value) instead
    of 1 (the actual VM flag), so Apple's DeviceCheck sees a physical machine and
    allows Apple ID sign-in on Sequoia/Tahoe VMs.
    """
    frag = "kp=p.setdefault(\"Kernel\",{}).setdefault(\"Patch\",[]); "
    for comment, find_hex, replace_hex in _APPLE_ID_BYPASS_PATCHES:
        frag += (
            f"_f=bytes.fromhex(\"{find_hex}\"); "
            "kp[:]=[x for x in kp if x.get(\"Find\")!=_f]; "
            "kp.append("
            "{"
            "\"Arch\":\"x86_64\","
            "\"Base\":\"\","
            f"\"Comment\":\"{comment}\","
            "\"Count\":1,"
            "\"Enabled\":True,"
            "\"Find\":_f,"
            "\"Identifier\":\"kernel\","
            "\"Limit\":0,"
            "\"Mask\":b\"\","
            "\"MaxKernel\":\"\","
            "\"MinKernel\":\"24.0.0\","
            f"\"Replace\":bytes.fromhex(\"{replace_hex}\"),"
            "\"ReplaceMask\":b\"\","
            "\"Skip\":0"
            "}); "
        )
    return frag


def _platforminfo_plist_keys(
    smbios_serial: str,
    smbios_uuid: str,
    smbios_mlb: str,
    smbios_rom: str,
    smbios_model: str,
) -> str:
    """Return inline python fragment to set PlatformInfo for Apple Services."""
    s_serial = _sanitize_smbios(smbios_serial)
    s_model = _sanitize_smbios(smbios_model, allow_comma=True)
    s_uuid = _sanitize_smbios(smbios_uuid)
    s_mlb = _sanitize_smbios(smbios_mlb)
    s_rom = _sanitize_smbios(smbios_rom)
    return (
        "pi=p.setdefault(\"PlatformInfo\",{}).setdefault(\"Generic\",{}); "
        f"pi[\"SystemSerialNumber\"]=\"{s_serial}\"; "
        f"pi[\"SystemProductName\"]=\"{s_model}\"; "
        f"pi[\"SystemUUID\"]=\"{s_uuid}\"; "
        f"pi[\"MLB\"]=\"{s_mlb}\"; "
        f"pi[\"ROM\"]=bytes.fromhex(\"{s_rom}\"); "
        "p[\"PlatformInfo\"][\"UpdateSMBIOS\"]=True; "
        "p[\"PlatformInfo\"][\"UpdateDataHub\"]=True; "
    )


def _plist_patch_script(
    verbose_boot: bool = False,
    is_amd: bool = False,
    apple_services: bool = False,
    smbios_serial: str = "",
    smbios_uuid: str = "",
    smbios_mlb: str = "",
    smbios_rom: str = "",
    smbios_model: str = "",
) -> str:
    """Return an inline python3 -c script that patches OpenCore's config.plist."""
    amd_patch = _amd_plist_keys() if is_amd else ""
    platforminfo = (
        _platforminfo_plist_keys(smbios_serial, smbios_uuid, smbios_mlb, smbios_rom, smbios_model)
        if apple_services and smbios_serial
        else ""
    )
    apple_id_bypass = _apple_id_bypass_patch_keys() if apple_services else ""
    boot_args = f"{BOOT_ARGS_BASE}{' -v' if verbose_boot else ''}"

    return (
        "python3 -c '"
        "import plistlib; "
        "import os; oc_dest=os.environ[\"OC_DEST\"]; "
        "f=open(oc_dest+\"/EFI/OC/config.plist\",\"rb\"); p=plistlib.load(f); f.close(); "
        "p[\"Misc\"][\"Security\"][\"ScanPolicy\"]=0; "
        "p[\"Misc\"][\"Security\"][\"DmgLoading\"]=\"Any\"; "
        "p[\"Misc\"][\"Security\"][\"SecureBootModel\"]=\"Disabled\"; "
        f"p[\"Misc\"][\"Boot\"][\"Timeout\"]={PICKER_TIMEOUT_INSTALL}; "
        "p[\"Misc\"][\"Boot\"][\"PickerAttributes\"]=17; "
        "p[\"Misc\"][\"Boot\"][\"HideAuxiliary\"]=True; "
        "p[\"Misc\"][\"Security\"][\"AllowSetDefault\"]=True; "
        "p[\"Misc\"][\"Boot\"][\"PickerMode\"]=\"External\"; "
        "p[\"Misc\"][\"Boot\"][\"PickerVariant\"]=\"Acidanthera\\\\Syrah\"; "
        "p[\"NVRAM\"][\"Add\"][\"7C436110-AB2A-4BBB-A880-FE41995C9F82\"][\"csr-active-config\"]=b\"\\x67\\x0f\\x00\\x00\"; "
        f"p[\"NVRAM\"][\"Add\"][\"7C436110-AB2A-4BBB-A880-FE41995C9F82\"][\"boot-args\"]=\"{boot_args}\"; "
        "p[\"NVRAM\"][\"Add\"][\"7C436110-AB2A-4BBB-A880-FE41995C9F82\"][\"prev-lang:kbd\"]=\"en-US:0\".encode(); "
        "nv_del=p.setdefault(\"NVRAM\",{}).setdefault(\"Delete\",{}); "
        "nv_del[\"7C436110-AB2A-4BBB-A880-FE41995C9F82\"]=[\"csr-active-config\",\"boot-args\",\"prev-lang:kbd\"]; "
        "p[\"NVRAM\"][\"WriteFlash\"]=True; "
        "p.setdefault(\"UEFI\",{}).setdefault(\"Quirks\",{})[\"RequestBootVarRouting\"]=True; "
        "[k.update(Enabled=True) for k in p.get(\"Kernel\",{}).get(\"Add\",[]) if \"VirtualSMC\" in k.get(\"BundlePath\",\"\")]; "
        "ka=p.setdefault(\"Kernel\",{}).setdefault(\"Add\",[]); "
        "os.path.isdir(oc_dest+\"/EFI/OC/Kexts/RestrictEvents.kext\") "
        "and (\"RestrictEvents.kext\" not in [k.get(\"BundlePath\") for k in ka]) "
        "and ka.append({\"Arch\":\"Any\",\"BundlePath\":\"RestrictEvents.kext\","
        "\"Comment\":\"Silence MacPro7,1 memory warning\",\"Enabled\":True,"
        "\"ExecutablePath\":\"Contents/MacOS/RestrictEvents\",\"MaxKernel\":\"\","
        "\"MinKernel\":\"\",\"PlistPath\":\"Contents/Info.plist\"}); "
        "[k.update(Enabled=True) for k in ka if \"RestrictEvents\" in k.get(\"BundlePath\",\"\")]; "
        + amd_patch
        + platforminfo
        + apple_id_bypass
        + "f=open(oc_dest+\"/EFI/OC/config.plist\",\"wb\"); plistlib.dump(p,f); f.close(); "
        "import sys; sys.stderr.write(\"config.plist patched\\n\")'"
    )


def _inject_restrictevents_script(opencore_path: Path) -> str:
    """Return bash snippet that adds RestrictEvents.kext to the EFI being built.

    The kext zip is normally pre-downloaded next to the OpenCore ISO. If it is
    missing (cached ISO, download phase skipped), curl it directly; if that
    also fails the build continues, since the fix is purely cosmetic.
    """
    zip_path = opencore_path.parent / RESTRICTEVENTS_ZIP
    return (
        f"export RE_ZIP={shquote(str(zip_path))}; "
        f"[ -f \"$RE_ZIP\" ] || curl -fsSL -o \"$RE_ZIP\" {shquote(RESTRICTEVENTS_URL)} "
        "|| echo 'WARN: RestrictEvents download failed'; "
        "if [ -f \"$RE_ZIP\" ]; then "
        "python3 -c '"
        "import os, zipfile; "
        "z=zipfile.ZipFile(os.environ[\"RE_ZIP\"]); "
        "names=[n for n in z.namelist() if n.startswith(\"RestrictEvents.kext/\")]; "
        "z.extractall(os.environ[\"OC_DEST\"]+\"/EFI/OC/Kexts\", members=names); "
        "import sys; sys.stderr.write(\"RestrictEvents.kext injected\\n\")' "
        "|| echo 'WARN: RestrictEvents.kext extraction failed, memory warning fix skipped'; "
        "else echo 'WARN: RestrictEvents.kext unavailable, memory warning fix skipped'; fi && "
    )


def _loop_cleanup_script(opencore_path: Path, dest: Path) -> str:
    """Return bash snippet for loop device trap and stale cleanup."""
    return (
        "SRC_LOOP=''; DEST_LOOP=''; "
        "OC_SRC=$(mktemp -d) && OC_DEST=$(mktemp -d) && export OC_SRC OC_DEST && "
        "trap 'umount $OC_SRC 2>/dev/null; umount $OC_DEST 2>/dev/null; "
        "[ -n \"$SRC_LOOP\" ] && losetup -d $SRC_LOOP 2>/dev/null; "
        "[ -n \"$DEST_LOOP\" ] && losetup -d $DEST_LOOP 2>/dev/null; "
        "rm -rf $OC_SRC $OC_DEST' EXIT; "
        "umount $OC_SRC 2>/dev/null; umount $OC_DEST 2>/dev/null; "
        f'for lo in $(losetup -j {shquote(str(opencore_path))} -O NAME --noheadings 2>/dev/null); do umount -l $lo* 2>/dev/null; losetup -d $lo 2>/dev/null; done; '
        f'for lo in $(losetup -j {shquote(str(dest))} -O NAME --noheadings 2>/dev/null); do umount -l $lo* 2>/dev/null; losetup -d $lo 2>/dev/null; done; '
    )


def _mount_source_oc_script(opencore_path: Path) -> str:
    """Return bash snippet to loop-mount the source OpenCore ISO."""
    return (
        f'SRC_LOOP=$(losetup -fP --show {shquote(str(opencore_path))}) && '
        "{ [ -b \"$SRC_LOOP\" ] || { echo 'ERROR: losetup failed for OpenCore source ISO. Hints: modprobe loop; losetup -a; ls /dev/loop*'; false; }; } && "
        f"{_partprobe_retry_snippet('SRC_LOOP')} && "
        "SRC_PART=$(blkid -o device $SRC_LOOP ${SRC_LOOP}p* 2>/dev/null "
        "| xargs -I{} sh -c 'blkid -s TYPE -o value {} 2>/dev/null | grep -q vfat && echo {}' "
        "| head -1); "
        "if [ -n \"$SRC_PART\" ]; then mount \"$SRC_PART\" $OC_SRC; "
        "else echo 'WARN: No vfat partition found on source ISO via blkid, trying raw mount'; mount $SRC_LOOP $OC_SRC; fi && "
        "{ mountpoint -q $OC_SRC || { echo \"ERROR: $OC_SRC is not mounted. Hints: file $SRC_LOOP; blkid $SRC_LOOP; dmesg | tail -5\"; false; }; } && "
    )


def _format_dest_oc_script(dest: Path) -> str:
    """Return bash snippet to create, format, and mount the destination OpenCore disk."""
    qp = shquote(str(dest))
    return (
        f'dd if=/dev/zero of={qp} bs=1M count={_OC_DISK_SIZE_MB} && '
        f'sgdisk -Z {qp} && '
        f'sgdisk -n 1:0:0 -t 1:EF00 -c 1:OPENCORE {qp} && '
        f'DEST_LOOP=$(losetup -fP --show {qp}) && '
        "{ [ -b \"$DEST_LOOP\" ] || { echo 'ERROR: losetup failed for OpenCore destination disk. Hints: modprobe loop; losetup -a; ls /dev/loop*'; false; }; } && "
        f"{_partprobe_retry_snippet('DEST_LOOP')} && "
        "{ [ -b \"${DEST_LOOP}p1\" ] || { echo \"ERROR: ${DEST_LOOP}p1 not found after partprobe. Hint: Try running the script again (slow storage)\"; false; }; } && "
        "mkfs.fat -F 32 -n OPENCORE ${DEST_LOOP}p1 && "
        "mount ${DEST_LOOP}p1 $OC_DEST && "
        "{ mountpoint -q $OC_DEST || { echo \"ERROR: $OC_DEST is not mounted. Hints: file ${DEST_LOOP}p1; blkid ${DEST_LOOP}p1; dmesg | tail -5\"; false; }; } && "
    )


def _build_oc_disk_script(
    opencore_path: Path, recovery_path: Path, dest: Path, macos: str,
    is_amd: bool = False, cores: int = 4, verbose_boot: bool = False,
    apple_services: bool = False, smbios_serial: str = "",
    smbios_uuid: str = "", smbios_mlb: str = "", smbios_rom: str = "",
    smbios_model: str = "",
) -> str:
    """Build a bash script that creates a GPT+ESP OpenCore disk with patched config."""
    plist_script = _plist_patch_script(
        verbose_boot=verbose_boot, is_amd=is_amd,
        apple_services=apple_services, smbios_serial=smbios_serial,
        smbios_uuid=smbios_uuid, smbios_mlb=smbios_mlb,
        smbios_rom=smbios_rom, smbios_model=smbios_model,
    )

    return (
        _loop_cleanup_script(opencore_path, dest)
        + _format_dest_oc_script(dest)
        + _mount_source_oc_script(opencore_path)
        # Copy OpenCore files (including hidden files)
        + "cp -a $OC_SRC/. $OC_DEST/ && "
        # Validate EFI structure was copied
        "{ [ -d $OC_DEST/EFI/OC ] || { echo 'ERROR: OpenCore ISO does not contain expected EFI/OC directory. ISO may be corrupt.'; false; }; } && "
        # Add RestrictEvents.kext (silences MacPro7,1 memory warning)
        + _inject_restrictevents_script(opencore_path)
        # Patch config.plist
        + plist_script + " && "
        # Fix plistlib self-closing tags that OpenCore's OcXmlLib rejects
        "sed -i 's|<array/>|<array></array>|g; s|<dict/>|<dict></dict>|g; s|<data/>|<data></data>|g' $OC_DEST/EFI/OC/config.plist && "
        # Hide OC partition from boot picker (shown only when user presses Space)
        "echo Auxiliary > $OC_DEST/.contentVisibility && "
        # Cleanup mounts (lazy unmount fallback for busy mounts)
        "{ umount $OC_SRC || umount -l $OC_SRC; } && losetup -d $SRC_LOOP && "
        "{ umount $OC_DEST || umount -l $OC_DEST; } && losetup -d $DEST_LOOP"
    )
